version: '3.9'

services:
    myhome:
        build:
            context:
            dockerfile: docker/server/Dockerfile
            image: "myhome"
            ports:
             - "3000:3000"
             
    db:
        build:
            context: docker/postgres
            dockerfile: ./Dockerfile
        image: "postgres:13"
        restart: always
        environment:
           - POSTGRES_USER=${POSTGRES_USER}
           - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
           - POSTGRES_DB=${POSTGRES_DB}
        ports:
           - ${POSTGRES_PORT}:5432